### ISSUE TITLE
Internal error: ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by kuku1234us** [dotlottie/player-component#257]
I tried to use DotLottiePlayer on a Next.js 13 barebone app with nothing but the DotLottiePlayer. Got the following error. I tried all versions from 1.3.0 to 1.6.3 all with same error. The player still plays but has some strange side effects.

```
 ⨯ node_modules\@dotlottie\react-player\dist\chunk-RRTNX2SD.js (1:33293) @ 
new bn
 ⨯ Internal error: ReferenceError: structuredClone is not defined
    at new bn (./node_modules/@dotlottie/react-player/dist/chunk-RRTNX2SD.js:18:33903)
    at eval (./node_modules/@dotlottie/react-player/dist/chunk-4TZKCMTH.js:14:78)
    at ok (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:65430)
    at Object.useState (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:67789)
    at t.useState (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:239329)
    at A (./node_modules/@dotlottie/react-player/dist/chunk-4TZKCMTH.js:14:73)
    at eval (./node_modules/@dotlottie/react-player/dist/chunk-4TZKCMTH.js:14:1136)
    at oZ (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:71093)
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:104584)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at aa (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:113776)
    at D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:102528
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:103006)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at o7 (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:72511)
    at D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77602
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77626)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at o7 (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:72511)
    at D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77602
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77626)
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:106481)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at aa (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:113776)
    at ao (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:112668)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109925)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:105120)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at o7 (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:72511)
    at D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77602
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77626)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at oQ (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:72092)
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:75508)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at o7 (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:72511)
    at D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77602
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:77626)
    at e (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:109576)
    at an (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:111554)
    at oQ (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:72092)
    at at (D:\projects\lottietest\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:11:75508)
null
```

**Comment by theashraf** [comment]
@kuku1234us The issue has been resolved in the latest release of @dotlottie/react-player (version 1.6.4).

Please inform us if you continue to experience any problems.

Thank you.

Related Issue: #256
