### ISSUE TITLE
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by Panoplos** [dotlottie/player-component#304]
React Version: `"react": "18.2.0"`
Player Version: `"@dotlottie/react-player": "^1.6.14",`
Error:

```
 ⨯ node_modules/@dotlottie/react-player/dist/chunk-XVC7DH25.js (4:1511) @ eval
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/makoto/Documents/Development/Web/heyai/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/makoto/Documents/Development/Web/heyai/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/makoto/Documents/Development/Web/heyai/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/components/Concierge/Hero.tsx:9:81)
    at (rsc)/./src/app/components/Concierge/Hero.tsx (/Users/makoto/Documents/Development/Web/heyai/.next/server/app/concierge/page.js:521:1)
    at __webpack_require__ (/Users/makoto/Documents/Development/Web/heyai/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/concierge/page.tsx:10:88)
    at (rsc)/./src/app/concierge/page.tsx (/Users/makoto/Documents/Development/Web/heyai/next/server/app/concierge/page.js:688:1)
    at Function.__webpack_require__ (/Users/makoto/Documents/Development/Web/heyai/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
null
```

DotLottie:
[try-it-arrow.lottie.zip](https://github.com/dotlottie/player-component/files/13987718/try-it-arrow.lottie.zip)

**Comment by Panoplos** [comment]
Found the issue. Needed `"use client"` in the component. Hopefully someone else running into this can find this issue thread quickly to save headache from not recognizing the obvious. Haha
